exports.categoryMap = [
    ["10xBitco.in", "Gambling"],
    ["1Coin.com", "Exchange"],
    ["50BTC.com", "Mining Pool"],
    ["777Coin.com", "Gambling"],
    ["796.com", "Exchange"],
    ["999Dice.com", "Gambling"],
    ["ASICMiner", "Mining Pool"],
    ["AbraxasMarket", "Darknet Market"],
    ["ActionCrypto.com", "Gambling"],
    ["AdmiralCoin.com", "Gambling"],
    ["AgoraMarket", "Darknet Market"],
    ["AllCoin.com", "Exchange"],
    ["AllCrypt.com", "Exchange"],
    ["AlphaBayMarket", "Exchange"],
    ["AnoniBet.com", "Gambling"],
    ["AntPool.com", "Mining Pool"],
    ["AnxPro.com", "Exchange"],
    ["BIToomBa.com", "Gambling"],
    ["BTC-e.com", "Exchange"],
    ["BTCC.com", "Exchange"],
    ["BTCCPool", "Mining Pool"],
    ["BTCGuild.com", "Mining Pool"],
    ["BTCJam.com", "Other"],
    ["BTCLend.org", "Other"],
    ["BTCOracle.com", "Gambling"],
    ["BTCPop.co", "Other"],
    ["BTCt.com", "Other"],
    ["BW.com", "Mining Pool"],
    ["BX.in.th", "Exchange"],
    ["BabylonMarket", "Darknet Market"],
    ["Banx.io", "Exchange"],
    ["BetChain.com-old", "Gambling"],
    ["BetMoose.com", "Gambling"],
    ["Betcoin.ag", "Gambling"],
    ["Betcoin.tm", "Gambling"],
    ["BetcoinDice.tm", "Gambling"],
    ["Betcoins.net", "Gambling"],
    ["BetsOfBitco.in", "Gambling"],
    ["Birwo.com-old", "Gambling"],
    ["Bit-x.com", "Exchange"],
    ["BitAces.me", "Gambling"],
    ["BitBargain.co.uk", "Exchange"],
    ["BitBay.net", "Exchange"],
    ["BitClix.com", "Other"],
    ["BitElfin.com", "Gambling"],
    ["BitKonan.com", "Exchange"],
    ["BitLaunder.com", "Other"],
    ["BitMillions.com", "Gambling"],
    ["BitMinter.com", "Mining Pool"],
    ["BitNZ.com", "Exchange"],
    ["BitPay.com", "Merchant Services"],
    ["BitStarz.com", "Gambling"],
    ["BitVC.com", "Exchange"],
    ["BitYes.com", "Exchange"],
    ["BitZillions.com", "Gambling"],
    ["BitZino.com", "Gambling"],
    ["Bitbond.com", "Other"],
    ["Bitcash.cz", "Exchange"],
    ["Bitcoin-24.com", "Exchange"],
    ["Bitcoin-Roulette.com", "Gambling"],
    ["Bitcoin.de", "Exchange"],
    ["BitcoinFog", "Scam"],
    ["BitcoinPokerTables.com", "Gambling"],
    ["BitcoinVideoCasino.com", "Gambling"],
    ["BitcoinVietnam.com.vn", "Exchange"],
    ["BitcoinWallet.com", "Hosted Wallet"],
    ["BitcoinWeBank.com", "Exchange"],
    ["Bitcoinica.com", "Exchange"],
    ["Bitcurex.com", "Exchange"],
    ["Bitfinex.com", "Exchange"],
    ["Bitfury.org", "Mining Pool"],
    ["Bitmit.net", "Other"],
    ["BitoEX.com", "Exchange"],
    ["Bitso.com", "Exchange"],
    ["Bitstamp.net", "Exchange"],
    ["Bittrex.com", "Exchange"],
    ["BlackBankMarket", "Darknet Market"],
    ["Bleutrade.com", "Exchange"],
    ["BlockTrades.us", "Exchange"],
    ["BlueSkyMarketplace", "Darknet Market"],
    ["Brawker.com", "Other"],
    ["Btc38.com", "Exchange"],
    ["BtcDice.com", "Gambling"],
    ["BtcEur.eu", "Exchange"],
    ["BtcExchange.ro", "Exchange"],
    ["BtcMarkets.net", "Exchange"],
    ["BtcTrade.com", "Exchange"],
    ["Btcst.com-pirateat40", "Scam"],
    ["Bter.com", "Exchange"],
    ["Bylls.com", "Merchant Services"],
    ["C-Cex.com", "Exchange"],
    ["CampBX.com", "Exchange"],
    ["CannabisRoadMarket", "Darknet Market"],
    ["Cavirtex.com", "Exchange"],
    ["Ccedk.com", "Exchange"],
    ["Cex.io", "Exchange"],
    ["ChBtc.com", "Exchange"],
    ["Chainroll.com", "Gambling"],
    ["ChangeTip.com", "Merchant Services"],
    ["CleverCoin.com", "Exchange"],
    ["CloudBet.com", "Gambling"],
    ["CloudHashing.com", "Mining Pool"],
    ["Coin-Swap.net", "Exchange"],
    ["Coin-Sweeper.com", "Gambling"],
    ["Coin.mx", "Exchange"],
    ["CoinApult.com", "Exchange"],
    ["CoinArch.com", "Exchange"],
    ["CoinBox.me", "Other"],
    ["CoinCafe.com", "Exchange"],
    ["CoinChimp.com", "Exchange"],
    ["CoinGaming.io", "Gambling"],
    ["CoinHako.com", "Exchange"],
    ["CoinHub.cz", "Exchange"],
    ["CoinJar.com", "Exchange"],
    ["CoinKite.com", "Merchant Services"],
    ["CoinMkt.com", "Exchange"],
    ["CoinMotion.com", "Exchange"],
    ["CoinPayments.net", "Merchant Services"],
    ["CoinRoyale.com", "Gambling"],
    ["CoinSpot.com.au", "Exchange"],
    ["CoinTrader.net", "Exchange"],
    ["CoinURL.com", "Other"],
    ["CoinVault", "Exchange"],
    ["CoinWorker.com", "Other"],
    ["Coinbroker.io", "Exchange"],
    ["Coingi.com", "Exchange"],
    ["Coinichiwa.com", "Gambling"],
    ["Coinimal.com", "Exchange"],
    ["Coinmate.io", "Exchange"],
    ["Coinomat.com", "Exchange"],
    ["Coinroll.com", "Gambling"],
    ["Coins-e.com", "Exchange"],
    ["Comkort.com", "Exchange"],
    ["CryptcoMiner.com", "Scam"],
    ["Crypto-Games.net", "Gambling"],
    ["Crypto-Trade.com", "Exchange"],
    ["CryptoBounty.com", "Gambling"],
    ["CryptoLocker", "Ransomware"],
    ["CryptoStocks.com", "Other"],
    ["Cryptomine.io", "Gambling"],
    ["Cryptonator.com", "High Risk Exchange"],
    ["Cryptonit.net", "Exchange"],
    ["Cryptopay.me", "Merchant Services"],
    ["Cryptorush.in", "Exchange"],
    ["Cryptsy.com", "Exchange"],
    ["Cubits.com", "Exchange"],
    ["DaDice.com", "Gambling"],
    ["Dagensia.eu", "Exchange"],
    ["DeepBit.net", "Mining Pool"],
    ["Dgex.com", "Exchange"],
    ["DiceBitco.in", "Gambling"],
    ["DiceCoin.io", "Gambling"],
    ["DiceNow.com", "Gambling"],
    ["DiceOnCrack.com", "Gambling"],
    ["Dispenser.tf", "Other"],
    ["DoctorDMarket", "Darknet Market"],
    ["EclipseMC.com", "Mining Pool"],
    ["Eligius.st", "Mining Pool"],
    ["EmpoEX.com", "Exchange"],
    ["Europex.eu", "Exchange"],
    ["EveryDice.com", "Gambling"],
    ["EvolutionMarket", "Darknet Market"],
    ["Exchange-Credit.ru", "Exchange"],
    ["ExchangeMyCoins.com", "Exchange"],
    ["Exchanging.ir", "Exchange"],
    ["Exmo.com", "Exchange"],
    ["FYBSG.com", "Exchange"],
    ["FairProof.com", "Gambling"],
    ["FaucetBOX.com", "Other"],
    ["FortuneJack.com", "Gambling"],
    ["FoxBit.com.br", "Exchange"],
    ["GHash.io", "Mining Pool"],
    ["Gatecoin.com", "Exchange"],
    ["Genesis-Mining.com", "Mining Pool"],
    ["GermanPlazaMarket", "Darknet Market"],
    ["GoCelery.com", "Exchange"],
    ["GreenRoadMarket", "Darknet Market"],
    ["HaoBTC.com", "Mining Pool"],
    ["HappyCoins.com", "Exchange"],
    ["Hashnest.com", "Exchange"],
    ["HelixMixer", "Mixer"],
    ["HitBtc.com", "Exchange"],
    ["HolyTransaction.com", "Exchange"],
    ["Huobi.com", "Exchange"],
    ["Ice-Dice.com", "Gambling"],
    ["Igot.com", "Exchange"],
    ["Indacoin.com", "Exchange"],
    ["Inputs.io", "Hosted Wallet"],
    ["Instawallet.org", "Hosted Wallet"],
    ["JetWin.com", "Gambling"],
    ["Just-Dice.com", "Gambling"],
    ["Justcoin.com", "Exchange"],
    ["Kano.is", "Mining Pool"],
    ["KnCMiner.com", "Mining Pool"],
    ["Korbit.co.kr", "Exchange"],
    ["Kraken.com", "Exchange"],
    ["LakeBTC.com", "Exchange"],
    ["Leancy.com", "Gambling"],
    ["LiteBit.eu", "Exchange"],
    ["Loanbase.com", "Other"],
    ["LocalBitcoins.com", "Exchange"],
    ["LuckyB.it", "Gambling"],
    ["Luno.com", "Exchange"],
    ["MPEx.co", "Exchange"],
    ["MaiCoin.com", "Exchange"],
    ["MasterXchange.com", "Exchange"],
    ["Matbea.com", "Exchange"],
    ["McxNOW.com", "Exchange"],
    ["MeXBT.com", "Exchange"],
    ["MercadoBitcoin.com.br", "Exchange"],
    ["MiddleEarthMarketplace", "Darknet Market"],
    ["MineField.BitcoinLab.org", "Gambling"],
    ["MinersCenter.com", "Scam"],
    ["MintPal.com", "Exchange"],
    ["MoonBit.co.in", "Other"],
    ["MyBitcoin.com", "Hosted Wallet"],
    ["NitrogenSports.eu", "Gambling"],
    ["NucleusMarket", "Darknet Market"],
    ["OKCoin.com", "Exchange"],
    ["OkLink.com", "Hosted Wallet"],
    ["OrderBook.net", "Exchange"],
    ["PandoraOpenMarket", "Darknet Market"],
    ["Paxful.com", "Exchange"],
    ["Paymium.com", "Exchange"],
    ["Peerbet.org", "Gambling"],
    ["PinballCoin.com", "Gambling"],
    ["Playt.in", "Gambling"],
    ["PocketDice.io", "Gambling"],
    ["PocketRocketsCasino.eu", "Gambling"],
    ["Polmine.pl", "Mining Pool"],
    ["Poloniex.com", "Exchange"],
    ["PonziCoin.co", "Gambling"],
    ["PrimeDice.com", "Gambling"],
    ["Purse.io", "Merchant Services"],
    ["QuadrigaCX.com", "Exchange"],
    ["Rollin.io", "Gambling"],
    ["SafeDice.com", "Gambling"],
    ["Satoshi-Karoshi.com", "Gambling"],
    ["SatoshiBet.com", "Gambling"],
    ["SatoshiCircle.com", "Gambling"],
    ["SatoshiDice.com", "Gambling"],
    ["SatoshiMines.com", "Gambling"],
    ["SatoshiRoulette.com", "Gambling"],
    ["SealsWithClubs.eu", "Gambling"],
    ["SecondsTrade.com", "Gambling"],
    ["SecureVPN.to", "Other"],
    ["SheepMarketplace", "Darknet Market"],
    ["SilkRoad2Market", "Darknet Market"],
    ["SilkRoadMarketplace", "Darknet Market"],
    ["SimpleCoin.cz", "Exchange"],
    ["SlushPool.com", "Mining Pool"],
    ["SmenarnaBitcoin.cz", "Exchange"],
    ["SpectroCoin.com", "Exchange"],
    ["StrongCoin.com-fee", "Hosted Wallet"],
    ["SuzukiDice.com", "Gambling"],
    ["SwCPoker.eu", "Gambling"],
    ["Telco214", "Mining Pool"],
    ["TheRockTrading.com", "Exchange"],
    ["UpDown.BT", "Gambling"],
    ["UrduBit.com-cold", "Exchange"],
    ["UseCryptos.com", "Exchange"],
    ["VaultOfSatoshi.com", "Exchange"],
    ["Vaultoro.com", "Exchange"],
    ["Vic-Socks.to", "Other"],
    ["VirWoX.com", "Exchange"],
    ["Vircurex.com", "Exchange"],
    ["WatchMyBit.com", "Other"],
    ["Xapo.com", "Hosted Wallet"],
    ["YABTCL.com", "Gambling"],
    ["YoBit.net", "Exchange"],
    ["Zyado.com", "Exchange"],
    ["ePay.info", "Other"],
    ["incoming", "Other"]
]
